name: Cache nixpkgs

on:
  workflow_dispatch:
    inputs:
      package:
        description: "nixpkgs package name to build"
        required: true
        type: string
      platform:
        description: "Runner platform"
        required: true
        type: choice
        options:
          - self-hosted
          - ubuntu-latest

jobs:
  build:
    runs-on: ${{ inputs.platform }}
    timeout-minutes: 360
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: gawakawa
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix build "nixpkgs#${PACKAGE}" --inputs-from .
        env:
          PACKAGE: ${{ inputs.package }}
